-- ============================================================
-- Real-Time Blood Donation System - Supabase + PostGIS Schema
-- Run this in Supabase: SQL Editor
-- Prerequisite: Enable PostGIS (Database > Extensions > postgis)
-- ============================================================

-- 1) Enable PostGIS (skip if already enabled via Dashboard)
CREATE EXTENSION IF NOT EXISTS postgis;

-- ------------------------------------------------------------
-- DONORS: with geography for 5km geofencing
-- latitude, longitude from app; location auto-set by trigger
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS donors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  email text UNIQUE NOT NULL,
  phone text,
  password text,
  blood_group text NOT NULL,
  city text,
  age int,
  last_donation_date date,
  is_available boolean DEFAULT true,
  latitude float,
  longitude float,
  location geography(Point, 4326),
  created_at timestamptz DEFAULT now()
);

-- If donors already existed without these columns, add them
ALTER TABLE donors ADD COLUMN IF NOT EXISTS latitude float;
ALTER TABLE donors ADD COLUMN IF NOT EXISTS longitude float;
ALTER TABLE donors ADD COLUMN IF NOT EXISTS location geography(Point, 4326);
ALTER TABLE donors ADD COLUMN IF NOT EXISTS is_available boolean DEFAULT true;

CREATE INDEX IF NOT EXISTS idx_donors_location ON donors USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_donors_blood_available ON donors(blood_group, is_available) WHERE is_available = true;

CREATE OR REPLACE FUNCTION donors_set_location()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
    NEW.location := ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)::geography;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS tr_donors_set_location ON donors;
CREATE TRIGGER tr_donors_set_location BEFORE INSERT OR UPDATE OF latitude, longitude ON donors
  FOR EACH ROW EXECUTE FUNCTION donors_set_location();

-- ------------------------------------------------------------
-- HOSPITALS (Blood Banks): location for 5km donor matching
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hospitals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  phone text,
  password text,
  city text,
  reg_id text,
  contact_person text,
  latitude float,
  longitude float,
  location geography(Point, 4326),
  created_at timestamptz DEFAULT now()
);

-- If hospitals already existed without these columns, add them
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS latitude float;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS longitude float;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS location geography(Point, 4326);

CREATE INDEX IF NOT EXISTS idx_hospitals_location ON hospitals USING GIST (location);

CREATE OR REPLACE FUNCTION hospitals_set_location()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
    NEW.location := ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)::geography;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS tr_hospitals_set_location ON hospitals;
CREATE TRIGGER tr_hospitals_set_location BEFORE INSERT OR UPDATE OF latitude, longitude ON hospitals
  FOR EACH ROW EXECUTE FUNCTION hospitals_set_location();

-- ------------------------------------------------------------
-- PATIENTS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  email text UNIQUE NOT NULL,
  phone text,
  password text,
  city text,
  created_at timestamptz DEFAULT now()
);

-- ------------------------------------------------------------
-- ADMINS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  password text,
  created_at timestamptz DEFAULT now()
);

-- ------------------------------------------------------------
-- BLOOD_REQUESTS: links patient, hospital; used for Instant Dispatch
-- hospital_id is bigint to match hospitals.id (bigint)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blood_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint REFERENCES patients(id),
  hospital_id bigint REFERENCES hospitals(id) NOT NULL,
  blood_group text NOT NULL,
  component text NOT NULL,
  units_required int NOT NULL,
  urgency text NOT NULL,
  required_by timestamptz,
  reason text,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

-- ------------------------------------------------------------
-- NOTIFICATIONS: for Real-time; recipient_key = 'donor_5', 'patient_3', 'hospital_2', 'admin_0'
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  recipient_key text NOT NULL,
  title text NOT NULL,
  body text,
  request_id bigint REFERENCES blood_requests(id),
  read_at timestamptz,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_key);

-- ------------------------------------------------------------
-- RPC: Smart Matching - Donors within 5km of hospital
-- Uses PostGIS ST_DWithin (distance in meters: 5000 = 5km)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_donors_within_5km(p_hospital_id bigint, p_blood_group text)
RETURNS TABLE (
  id bigint,
  full_name text,
  email text,
  phone text,
  blood_group text,
  city text,
  age int,
  last_donation_date date,
  is_available boolean,
  distance_meters float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    d.id,
    d.full_name,
    d.email,
    d.phone,
    d.blood_group,
    d.city,
    d.age,
    d.last_donation_date,
    d.is_available,
    ST_Distance(d.location::geography, h.location::geography)::float as distance_meters
  FROM donors d
  CROSS JOIN hospitals h
  WHERE h.id = p_hospital_id
    AND d.blood_group = p_blood_group
    AND d.is_available = true
    AND d.location IS NOT NULL
    AND h.location IS NOT NULL
    AND ST_DWithin(d.location::geography, h.location::geography, 5000)
  ORDER BY distance_meters;
$$;

-- ------------------------------------------------------------
-- Enable Realtime for notifications (for Real-time feature)
-- In Dashboard: Database > Replication > Add notifications
-- Or run:
-- ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
-- ------------------------------------------------------------
-- ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
