-- ============================================================
-- Inventory System & Enhanced Instant Dispatch
-- ============================================================

-- ------------------------------------------------------------
-- INVENTORY: Track blood units by hospital, blood group, component
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint REFERENCES hospitals(id) ON DELETE CASCADE NOT NULL,
  blood_group text NOT NULL,
  component text NOT NULL,
  units_available int DEFAULT 0 CHECK (units_available >= 0),
  units_reserved int DEFAULT 0 CHECK (units_reserved >= 0),
  last_updated timestamptz DEFAULT now(),
  UNIQUE(hospital_id, blood_group, component)
);

CREATE INDEX IF NOT EXISTS idx_inventory_hospital ON inventory(hospital_id);
CREATE INDEX IF NOT EXISTS idx_inventory_lookup ON inventory(hospital_id, blood_group, component);

-- Function to update last_updated timestamp
CREATE OR REPLACE FUNCTION update_inventory_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_updated = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_inventory_timestamp
  BEFORE UPDATE ON inventory
  FOR EACH ROW
  EXECUTE FUNCTION update_inventory_timestamp();

-- ------------------------------------------------------------
-- DONOR_RESPONSES: Track donor responses to blood requests
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS donor_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint REFERENCES blood_requests(id) ON DELETE CASCADE NOT NULL,
  donor_id bigint REFERENCES donors(id) ON DELETE CASCADE NOT NULL,
  response text NOT NULL CHECK (response IN ('accepted', 'declined', 'pending')),
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(request_id, donor_id)
);

CREATE INDEX IF NOT EXISTS idx_donor_responses_request ON donor_responses(request_id);
CREATE INDEX IF NOT EXISTS idx_donor_responses_donor ON donor_responses(donor_id);

-- Update timestamp trigger
CREATE TRIGGER tr_donor_responses_timestamp
  BEFORE UPDATE ON donor_responses
  FOR EACH ROW
  EXECUTE FUNCTION update_inventory_timestamp();

-- ------------------------------------------------------------
-- DONATIONS: Track completed donations
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_id bigint REFERENCES donors(id) NOT NULL,
  request_id bigint REFERENCES blood_requests(id),
  hospital_id bigint REFERENCES hospitals(id) NOT NULL,
  blood_group text NOT NULL,
  component text NOT NULL,
  units int DEFAULT 1,
  donation_date date DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_donations_donor ON donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_hospital ON donations(hospital_id);
CREATE INDEX IF NOT EXISTS idx_donations_date ON donations(donation_date);

-- ------------------------------------------------------------
-- Update blood_requests table to track fulfillment
-- ------------------------------------------------------------
ALTER TABLE blood_requests ADD COLUMN IF NOT EXISTS units_fulfilled int DEFAULT 0;
ALTER TABLE blood_requests ADD COLUMN IF NOT EXISTS fulfilled_at timestamptz;
ALTER TABLE blood_requests ADD COLUMN IF NOT EXISTS donor_id bigint REFERENCES donors(id);

-- Add check constraint
ALTER TABLE blood_requests ADD CONSTRAINT check_units_fulfilled 
  CHECK (units_fulfilled >= 0 AND units_fulfilled <= units_required);

-- ------------------------------------------------------------
-- Function: Auto-update inventory when donation is recorded
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_inventory_on_donation()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO inventory (hospital_id, blood_group, component, units_available)
  VALUES (NEW.hospital_id, NEW.blood_group, NEW.component, NEW.units)
  ON CONFLICT (hospital_id, blood_group, component)
  DO UPDATE SET 
    units_available = inventory.units_available + NEW.units,
    last_updated = now();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_donation_inventory
  AFTER INSERT ON donations
  FOR EACH ROW
  EXECUTE FUNCTION update_inventory_on_donation();

-- ------------------------------------------------------------
-- Function: Auto-decrement inventory when request is fulfilled
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION decrement_inventory_on_fulfillment()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'fulfilled' AND OLD.status != 'fulfilled' THEN
    UPDATE inventory
    SET units_available = units_available - NEW.units_fulfilled,
        units_reserved = GREATEST(0, units_reserved - NEW.units_fulfilled)
    WHERE hospital_id = NEW.hospital_id
      AND blood_group = NEW.blood_group
      AND component = NEW.component
      AND units_available >= NEW.units_fulfilled;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_request_fulfillment
  AFTER UPDATE OF status ON blood_requests
  FOR EACH ROW
  EXECUTE FUNCTION decrement_inventory_on_fulfillment();

-- ------------------------------------------------------------
-- Enable Realtime for inventory and donor_responses
-- ------------------------------------------------------------
-- ALTER PUBLICATION supabase_realtime ADD TABLE inventory;
-- ALTER PUBLICATION supabase_realtime ADD TABLE donor_responses;
-- ALTER PUBLICATION supabase_realtime ADD TABLE donations;
