-- ============================================================
-- Ensure inventory table exists (fix schema cache issue)
-- ============================================================

-- Create inventory table if it doesn't exist
CREATE TABLE IF NOT EXISTS inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id bigint REFERENCES hospitals(id) ON DELETE CASCADE NOT NULL,
  blood_group text NOT NULL,
  component text NOT NULL,
  units_available int DEFAULT 0 CHECK (units_available >= 0),
  units_reserved int DEFAULT 0 CHECK (units_reserved >= 0),
  last_updated timestamptz DEFAULT now(),
  UNIQUE(hospital_id, blood_group, component)
);

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_inventory_hospital ON inventory(hospital_id);
CREATE INDEX IF NOT EXISTS idx_inventory_lookup ON inventory(hospital_id, blood_group, component);

-- Function to update last_updated timestamp (if not exists)
CREATE OR REPLACE FUNCTION update_inventory_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_updated = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger if it doesn't exist
DROP TRIGGER IF EXISTS tr_inventory_timestamp ON inventory;
CREATE TRIGGER tr_inventory_timestamp
  BEFORE UPDATE ON inventory
  FOR EACH ROW
  EXECUTE FUNCTION update_inventory_timestamp();
