-- Migration: Refresh schema cache for donor_responses table
-- This ensures the table is accessible via Supabase PostgREST API

-- Ensure donor_responses table exists (should already exist from 0002)
CREATE TABLE IF NOT EXISTS donor_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint REFERENCES blood_requests(id) ON DELETE CASCADE NOT NULL,
  donor_id bigint REFERENCES donors(id) ON DELETE CASCADE NOT NULL,
  response text NOT NULL CHECK (response IN ('accepted', 'declined', 'pending')),
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(request_id, donor_id)
);

-- Ensure indexes exist
CREATE INDEX IF NOT EXISTS idx_donor_responses_request ON donor_responses(request_id);
CREATE INDEX IF NOT EXISTS idx_donor_responses_donor ON donor_responses(donor_id);

-- Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';
