-- Migration: Refresh schema cache for donations table
-- This ensures the table is accessible via Supabase PostgREST API

-- Ensure donations table exists (should already exist from 0002)
CREATE TABLE IF NOT EXISTS donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_id bigint REFERENCES donors(id) NOT NULL,
  request_id bigint REFERENCES blood_requests(id),
  hospital_id bigint REFERENCES hospitals(id) NOT NULL,
  blood_group text NOT NULL,
  component text NOT NULL,
  units int DEFAULT 1,
  donation_date date DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now()
);

-- Ensure indexes exist
CREATE INDEX IF NOT EXISTS idx_donations_donor ON donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_hospital ON donations(hospital_id);
CREATE INDEX IF NOT EXISTS idx_donations_date ON donations(donation_date);
CREATE INDEX IF NOT EXISTS idx_donations_donor_date ON donations(donor_id, donation_date DESC);
CREATE INDEX IF NOT EXISTS idx_donations_hospital_date ON donations(hospital_id, donation_date DESC);
CREATE INDEX IF NOT EXISTS idx_donations_request ON donations(request_id) WHERE request_id IS NOT NULL;

-- Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';
